version: '2'
services:
    bubblemap-app:
        image: bubblemap
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bubblemap-mysql:3306/bubblemap?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bubblemap-mysql:
        extends:
            file: mysql.yml
            service: bubblemap-mysql
